An extensive guide on how to discover new music. TBC.

* How does new music appear?
As silly as it sounds, some people create music and then decide to share
it to the public.
It can be shared on various supports, digital (a file, mp3, wav, aif, ogg, flac
etc.), CD, tape, vinyl, and the same music can be released on many
supports.
Those suports have different properties, some make it easy to share
the music. Some put emphasis on the sound quality or the sonic
experience.
In any case what matters is that it gets to an audience enjoying it,
so combine.

* A method to discover new music organically, and learn your tastes
** same artist
You liked something that artist did, she/he/they possibly have other projects you
might enjoy.
Also note that the bassist, trumpetist, backing vocal of an act can
have a solo project, or collaborate with other people. Don't
just look at the big names, dig into those who in the shadow creating
those grooves like.
** same label
A label is mainly one or a group of person puting energy and
time in finding music and artists they like, and working together with
them so their music is being compiled and distributed to reach other
people who might enjoy and keep that flow of creation going.
Find a track you like, find the album.
** new styles and genres
You've been listening to rock, house, classic or raggae for a while now. There
is definitely something aside that you will get to love. It maybe even
doesn't have a name yet. Sure the beat is not quite the same, but give
yourself a little time moving some of the rocks surrounding your new
gold. Let pre-constructed opinion asides, there are streams out there that mixes
what you already enjoy and what you will get to love.
** save what you find
Buy music to listen at home. Play it on your computer or turntables,
organize it in shelves or in folders, create playlists offline or
online, but store what you find and start building your collection of
good tunes.

* Some sources to stumple upon new discoveies
All those sources should be combined.
** From home
*** Discogs
A community generated encyclopedia. Everything that can be know about
a recording should be found there. If you know something that cannot
there be found, you have to put it, for the sake of knowledge sharing!
Click the labels, different artists who made that record possible,
listen to all tracks on an album, look at other users created list in
which this record is. There are many ways you can get serendipity
started.
*** Wikipedia
The good old, giving you an overview of an artist, a genre, style,
era. Click on those links, get lost, learn and explore, copy paste
name in Youtube or Spotify, listen.
*** Youtube
Definitely one of the place where it is the easiest to listen to
music. Start listening to something you know already; then listen to
the side recommandation, other music from the same artists, other
tracks that are suggested that user also listened.
Youtube has developed a crazy algorithm which as been fueled by a
constant and massive ammount of data we give it while browsing the
site. The result is auto-generating lists of somehow related music.
*** Magazine and blogs
There are many magazines about music, talking about releases of new or
old music, generalist or specialized. Jazz, raggae, techno, look out
for yours.
*** Radios
Maybe the good old FM radio does not satisfy you any longer? No
worries, there are plenty of web based radios with dedicated people
willing to share the good tunes. Less ads, more music from more tastes.
*** Radio4000
A good tool to save and learn from your music discoveries, it is also
a nice spot to follow other musical explorations and get inspired by
other humans audio journeys.

** Outside of home 
*** Go to record shops
Those guys are spending their days listening to music, expert
diggers, they've dedicated their life to finding and shring the
grooves. Find some you'll be ready to trust and get their dope.
*** Go to parties, concerts and festivals
Same here. A party, concert or festival starts to exist because
someone wanted to share good music and good acts. There is high chance
those person are also willing to create for you a unique moment in
time and space you won't forget.

* Conclusion
This list should and will be a forever work in progress.
Share your discoveries online and offline.
Listen to more music, at your workplace or at home, on headphones or
speakers, go enjoy acts at venues.
Start creating your music, alone or together, with your name or
anonymously, make it available to listen.
Peace
